### ISSUE TITLE
Runtime dynamic forms from GraphQL schemas

### ISSUE THREAD

**Issue by pontusr** [formql/formql#92]
Hi Juan,

Thanks for your great work on this so far!

I'd like to propose a new feature where you could add a list of forms/layouts for all queries/mutations in a GraphQL introspection schema simply by providing a uri to the schema.

These dynamic forms would be ready for immediate use by being data-bound and having the basic validations already in place. As such they would serve primarily two use cases:

1. In many projects users (or often us the developers) have to perform simple CRUD operations directly against databases and so on many iterations into development. A reasonably user-friendly way of manipulating backend data using these dynamic forms would prevent this.
2. Starting the design-work on basic but already working forms and manipulating these using the editor considerably lowers the complexity and effort to create a large number of forms. 

There are many interesting challenges to solve here, for example:
*matching of queries and mutations to forms
*managing which forms (dynamic vs customized) should be available to "viewers".

I would be happy to try and do some work on this if you think FormQL is the right place for it?

**Comment by jstoppa** [comment]
Thanks so much for proposing this feature, it's a great idea!

I originally created this library with the Apollo client but then I decided to make the service implementation up to the developer in case they want to use it with a normal RESTFul API (I documented the service in [here](https://github.com/formql/formql/wiki/Creating-the-interfacing-service)). I always wanted to make sure the editor remains separated from the core library, this is to try to make @formql/core as smaller as possible so when running in production you don't need to carry the overhead of the editor.

Back to your question, I think FormQL is definitely the right place for your idea. I did look at how [GraphQL Editor](https://github.com/graphql/graphiql) work and checked how I could integrate it with the FormQL editor, I thought user being able to write a query and then perhaps "drag" fields from the result into the form, the FormQL editor can automatically sort out the binding to the field selected. The editor is not strongly typed at the moment, I always thought about getting everything wired up first and then introduce as much validation as possible like the ability to select the schema from a list of fields, I also thought at some point to integrate with something like swagger for normal RESTful API.

I have to admit that I left the library a bit unattended since COVID started but I really want to get back to it this month, I have a few PRs that I've been testing locally but didn't get to finish yet. I've also been actively looking for people that want to get involved on building FormQL so if you are interested then you are more than welcome.

How do you envision your feature being implemented? Would the user select the data source type in the editor, add the uri and then have a list of fields that can be added to the form? (e.g. I show below where you select the data source in a form, the type of data source is something I wanted to make an enum with RESTful and GraphQL as options (see FormDataSource model [here](https://github.com/formql/formql/blob/6b8e47a5ed85c2decfea48e33bbf9540967ee2f3/packages/core/src/models/form-window.model.ts#L16))
![image](https://user-images.githubusercontent.com/1074171/96386644-61e28800-1194-11eb-83c3-bbee53c9eaf9.png)
I sense you want something even more programmatic than that, it looks like you are proposing to have a list of predefined queries that you can use in your form?

In any case, I can definitely point you in the right direction, if you can elaborate then we can put some thoughts on how to build it

Juan

**Comment by LucianViana** [comment]
I'm trying to standardize the query by dynamodb, which should be simple queries and must meet the creation of a form for a product category for example we have json:
![image](https://user-images.githubusercontent.com/32082287/98287971-e569ea80-1f84-11eb-8b5f-a7bdccdc2754.png)
as you explain on this site i want to adapt the backend to formql with your help: https://aws.amazon.com/pt/blogs/database/how-sgk-simplified-the-data-structure-of-a-highly-dynamic-workload-by-migrating-from-an-rdbms-to-amazon-dynamodb/

and if you can give me the direction as you said in the previous conversation I would be grateful.

**Comment by jstoppa** [comment]
@LucianViana 
Not sure if I understand what you are trying to do but I put a [very simple example in stackblitz](https://stackblitz.com/edit/simple-form-example)


This example has 2 fields and a save button. Worth noting in the example below the save button to save the form definition and the save button that is on the form to save your data
![image](https://user-images.githubusercontent.com/1074171/98301658-08ab8e80-1fb3-11eb-82e8-da873a34fe04.png)

I made that example to store the data in local storage, this is simply to "simulate" as if your local storage was your webservice.

The idea with FormQL is that you design your form by dragging and dropping "components" in the form, you do that by dragging the third button on the left hand side (if you hover over the buttons, it tells you what they do)
![simpleForm](https://user-images.githubusercontent.com/1074171/98302294-0b5ab380-1fb4-11eb-83b6-f542d025d030.gif)

once you build your form, you click on the pencil button and define what component you want to use (simple field, date picker, picklist, etc) and then define your "schema", that is the mapping to a JSON Data object
![simpleForm2](https://user-images.githubusercontent.com/1074171/98302686-c5521f80-1fb4-11eb-8df0-9af42afcbcdb.gif)

if I now type something in the form and press save, the data is stored in local storage
![simpleForm3](https://user-images.githubusercontent.com/1074171/98303670-67bed280-1fb6-11eb-92a1-433ccb46b0cd.gif)

you might have also noticed that if I press the save button on the top to save my form definition, it will push the change to the local storage too
![simpleForm4](https://user-images.githubusercontent.com/1074171/98303958-f6335400-1fb6-11eb-8a5d-6042a4a587a6.gif)

this specific example has been configured in a way that your parameters determine the name of the form you are editing and the id of the record you want to save
![image](https://user-images.githubusercontent.com/1074171/98304105-3b578600-1fb7-11eb-865b-95d27725d977.png)

if you then remove the word edit, you can see the form in view mode (that's how your users will see/use your form)
![simpleForm5](https://user-images.githubusercontent.com/1074171/98304409-d51f3300-1fb7-11eb-888f-cb27d1c84490.gif)

FormQL doesn't force you to pass the form name and id through the URL all the time, I've just configured this specific example in that way to explain how FormQL works.

Back to your question, how would you implement the integration with DynamoDB? you just need to create a class that implements the IFormQLService interface and implements the getData/saveData and getForm/saveForm to connect to your backend of choice (you can see the implementation of the local storage [here](https://stackblitz.com/edit/formql-morgatgecalculator-final?file=src%2Fapp%2Fapp-service.ts), it's also documented in [this wiki](https://github.com/formql/formql/wiki/Creating-the-interfacing-service)). getData will be called when the form attempts to get the data to populate on the form and saveData when the user presses the Save button. In the same way getForm will be called when FormQL attempts to load the form definition and saveForm when the user clicks on the button on the top to save the form definition.

The philosophy behind FormQL is to help you build forms quickly by using the editor without having to write tons of code (you can read [here](https://github.com/formql/formql/wiki/FormQL-Editor) how the editor works). It also gives you the ability to write your own componentes and build more complex scenarios (see this [Mortgage Calculator implemented in FormQL](https://stackblitz.com/edit/formql-morgatgecalculator-final) which I also explained it in [this blog](https://medium.com/angular-in-depth/creating-an-interactive-mortgage-calculator-with-formql-a87e79886ff)

I hope it helps

**Comment by LucianViana** [comment]
Unbound breakpoint "problem debug in Visual Studio":

Hi, I can't debug in visual studio, do you have any tips to help?
The files cannot find the path, could it be because the compiled files are in another path?
My lauch.json:
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "chrome",
      "request": "launch",
      "name": "Launch Chrome",
      "url": "http://localhost:4200/",
      "webRoot": "${workspaceFolder}",
      "sourceMaps": true,
       "sourceMapPathOverrides": {
        "*": "${webRoot}/apps/angular/app/src/*"
       }
   },
    {
      "type": "node",
      "request": "launch",
      "name": "Jest Test",
      "program": "${workspaceFolder}/node_modules/jest/bin/jest",
      "args": [
        "--runInBand"
      ],
      "console": "integratedTerminal",
      "internalConsoleOptions": "neverOpen"
    }
  ]
}
note:
Other people have reported the same problem, but it seems that I am not alone in this problem.
example:
https://github.com/microsoft/vscode/issues/102493

**Comment by LucianViana** [comment]
Now I found that I can only select if it is a "js" file, as shown in the image below, it seems that there may be a solution out there, maybe if we change the build structure, but here is a tip to help other people who may have same problem to debug:
![debug](https://user-images.githubusercontent.com/32082287/99974308-80353800-2d7f-11eb-93ff-721134fc4e8f.png)

**Comment by LucianViana** [comment]
Hi Juan,
I know it can be support but I didn't find it on formql.io where to ask, but I'm trying to access an external http and the error happens below, would it be any restrictions that formql still has or not?

Error:
"TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functio"

this.http.get(`http://api.openweathermap.org/data/2.5/weather?q=London,uk&APPID=7facebd2cd201249fb820ac63ed905e5`);

    > 40 |     expect(actualDataReturned).toEqual(mockData);
         |                                ^
      41 |     done();
      42 |   });
      43 |     //service.getProducts().subscribe((products) => {

      at apps/angular/app/src/app/product.service.spec.ts:40:32
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:391:26)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/proxy.js:129:39)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:390:52)
      at Zone.Object.<anonymous>.Zone.run (node_modules/zone.js/dist/zone.js:150:43)
      at Object.<anonymous> (node_modules/jest-preset-angular/zone-patch/index.js:53:29)

thanks.

**Comment by jstoppa** [comment]
I'm not sure about your setup, looks like you are trying to mock some data with jest? in any case, formql shouldn't have any problem to work with that API. Maybe something related to the API called as in [this StackOverflow question](https://stackoverflow.com/questions/52298691/getting-typeerror-caller-callee-and-arguments-properties-may-not-be-acc)?

I just created a quick example in stackblitz 
https://stackblitz.com/edit/simple-form-weather-api?file=src%2Fapp%2Fapp-service.ts

You can see below I added your URL using SSL (e.g. https otherwise stackblitz will block it) and the data is populated correctly in the form
![image](https://user-images.githubusercontent.com/1074171/101090270-4b5e8780-35ae-11eb-80a5-80805ee8e93b.png)

I've just had to get the mapping aligned with the API response
![image](https://user-images.githubusercontent.com/1074171/101090519-adb78800-35ae-11eb-82b0-dc6bbfa71eae.png)

hope it helps
